### ISSUE TITLE
Heavy non-static dependency on SQL/SQLite

### ISSUE THREAD

**Issue by parkr** [sourcegraph/checkup#102]
Hi! I build a Docker image for `checkup` for my use. In order to get the most up-to-date releases, I build from source and choose a Git revision to build from.

I recently upgraded my automatic builds to Actions v2 and discovered (since it hasn't run in a while) that the more recent versions of `checkup` require gcc, sqlite, and libc! It also takes a full 90 seconds to compile, which is insane for a small Go app. I was super puzzled since this was meant to be a really simple app and discovered that #61 had been merged adding a mandatory SQL dependency. The compile dependencies & compile time increase are due to this addition.

Is there any way to add a build flag to remove this dependency? I use GitHub as a storage backend and have no need for SQL. Maybe we can make heavier dependencies like this optional.

**Comment by parkr** [comment]
:revolving_hearts:

**Comment by titpetric** [comment]
I think the main issue was the SQLite dependency, which requires CGO. Beyang closed the issue as the master already added an opt-in build for this, but additional refactors may push the compile time a bit. Tag me if you notice some issues.

**Comment by parkr** [comment]
> I think the main issue was the SQLite dependency, which requires CGO.

This was part of it. The other part was how long compilation took. I run these builds in GitHub Actions and noticed how long it took to build. Today, it takes 75s to do the entire process of linting the Dockerfile, pulling down the base image, building the image and quickly testing it. This is a dramatic improvement since it was 90s for _just the Go binary compilation_ before.
