### ISSUE TITLE
self-host Google Fonts

### ISSUE THREAD

**Issue by DanielRuf** [sourcegraph/checkup#114]
checkup should not load fonts from Google Fonts (`https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,700`) but provide them in the statuspage.

See https://google-webfonts-helper.herokuapp.com/fonts/source-sans-pro?subsets=latin for the correct way (only load woff2 and woff - in this order - and without the `local` rule).

**Comment by titpetric** [comment]
I'll go ahead and close this, it's a non-issue. Font's get updated on CDNs as required, and there is little sense in keeping a mirror of these assets.

**Comment by DanielRuf** [comment]
Well, it's a bit problematic regarding GDPR. And CDNs can go down and with partitioned caches it does not improve the performance too.

At least we should have an option or documentation part to host them ourself.

Fonts do not change so fast.

**Comment by titpetric** [comment]
If anything, I might take a look at downgrading the font experience to a
relatively standard set of system fonts and fallbacks.

Customizing status pages isn’t high on the list of goals for checkup yet,
so we definitely wouldn’t like to pull in documentation for that. While
this may eventually happen, I’m prioritizing my work on storage, notifiers
and checkers which all need some TLC.

It’s more likely the status page will be fully rewritten at some point,
including a more sensible approach to customization (css themes, etc.)

BR

**Comment by DanielRuf** [comment]
Alternatively you can get them from https://google-webfonts-helper.herokuapp.com/fonts
