### ISSUE TITLE
make build-sql throwing error as cannot use -o with multiple packages

### ISSUE THREAD

**Issue by reidharry** [sourcegraph/checkup#121]
Here is the command line output when run `make build-sql`

```
make build-sql
go fmt ./...
go mod tidy
go build -o builds/ -tags sql ./cmd/...
go build: cannot use -o with multiple packages
make: *** [build-sql] Error 1
```

Thanks in advance.

**Comment by rrjanbiah** [comment]
Getting same issue. 

@titpetric Do you have any idea? TIA

**Comment by titpetric** [comment]
I’ll send a patch up asap, likely tomorrow.

**Comment by rrjanbiah** [comment]
@titpetric Thank you so much for your quick reply

**Comment by titpetric** [comment]
Could you please verify your go version for me? Like so:

```
# go version
go version go1.14 linux/amd64
```

**Comment by reidharry** [comment]
@titpetric 

go version is 1.12,

```
go version
go version go1.12.7 darwin/amd64
```

**Comment by rrjanbiah** [comment]
> Could you please verify your go version for me? Like so:

Mine is `go version go1.12.7 linux/amd64`

Do you mean that I need to upgrade?

**Comment by titpetric** [comment]
Correct. Current target version is already Go 1.14, as the build to folder output features have been implemented against that ([golang/go issue](https://github.com/golang/go/issues/14295)).

I could degrade the Makefile commands a bit, but you will need at least go 1.13 due to go modules. Is it reasonable to expect a bump to 1.14?

**Comment by rrjanbiah** [comment]
@titpetric Sure, will upgrade and check. Thank you so much for your help.

**Comment by reidharry** [comment]
@titpetric After upgraded to Go 1.14 build is working. Thank you.
