### ISSUE TITLE
Wishlist: Sample configuration file that explains all possibilities of checkup

### ISSUE THREAD

**Issue by rrjanbiah** [sourcegraph/checkup#125]
For example, checkup has `must_contain` as mentioned in https://tryingtobeawesome.com/checkup/ but that doesn't seem to be documented in the repo. For a quick thing, a sample config.json with all such possibilities will help

**Comment by titpetric** [comment]
The full config structures are linked from the readme (e.g.
https://godoc.org/github.com/sourcegraph/checkup/check/http). All the
individual flags are listed there for each checker/storage/notifier.

If you feel you can improve the docs, PR’s are more than welcome.

**Comment by prcmt** [comment]
>The full config structures are linked from the readme (e.g.
>https://godoc.org/github.com/sourcegraph/checkup/check/http). All the
>individual flags are listed there for each checker/storage/notifier.

That page is a 404.

**Comment by rrjanbiah** [comment]
@prcmt Works for me https://godoc.org/github.com/sourcegraph/checkup/check/http

**Comment by prcmt** [comment]
@rrjanbiah Huh, must've been a temporary issue with godoc.org. :)

**Comment by titpetric** [comment]
Closing this issue as non-actionable at this time. The README and the individual linked godoc pages are the current/best source of documentation. Currently, user documentation is a low priority, and some technical knowledge is required, but PRs are welcome. Be sure to sign them in agreement with the new DCO.
