### ISSUE TITLE
documentation for how to use subdirectory for checks

### ISSUE THREAD

**Issue by heylix** [sourcegraph/checkup#135]
Hi, I added a subdirectory `checks/` and created `.json` files there. Do I use multiple `-c` flags to use them? How's the syntax of the files, does every file need a `checkers` array?

I successfully executed `podman exec -ti checkup_checkup_1 checkup -c checks/test.json` with the `checkers` array. But how do I integrate this into the main status page?

Apparently you can store the check results with `podman exec -ti checkup_checkup_1 checkup -c checks/ -c checkup.json --store`, so first loading the checks from the `checks/` directory, then the config for storage etc. and then storing it.

This should probably be explained in the docs. A few more examples would be nice too.

EDIT: oh, apparently you don't use a subdirectory for defining checks, but for storing them. You can't currently retrieve stored checks from a postgresql database as far as I can see it?

**Comment by ale624** [comment]
Yeah I agree the documentation is pretty bad. 

i've managed to get most of what I wanted working just via trial and error.
the SQL database portion was removed a couple versions ago if i do recall correctly.

**Comment by titpetric** [comment]
From running `checkup --help` (as mentioned in the readme):

~~~
Checkup will always look for a checkup.json file in
the current working directory by default and use it.
You can specify a different file location using the
--config/-c flag.
~~~

You can have any number of checkup configs which can have the same storage outputs, and you can run them independently. You can only pass a single `-c` flag to checkup. I forget the use case why you'd want that in particular, but you can do it like that.

As far as reading the checks from SQL (or any removal of docs), the README does say the following:

https://github.com/sourcegraph/checkup/#checkup-status-page

~~~
Checkup now has a local HTTP server that supports serving checks stored in:

FS (local filesystem storage),
MySQL
PostgreSQL
SQLite3 (not enabled by default)

You can run checkup serve from the folder which contains checkup.json and the statuspage/ folder.
~~~

Checkup did not have support for reading checks from SQL before a few months ago. Also the SQL database portion wasn't removed from the README at any point.

Improvements for documentation are welcome. Open up a PR if you feel like you can improve it in any way. Thanks :+1:
