### ISSUE TITLE
Adding headers to checker section result in "cannot unmarshal string" error.

### ISSUE THREAD

**Issue by xoraingroup** [sourcegraph/checkup#137]
Hi,

I added following headers snippet to checkers section.

```javascript
{
    "checkers": [
        {
    		"type": "http",
    		"endpoint_name": "Test API",
    		"endpoint_url": "https://xxxx.xxxx.xxxxx/api/v1",
		"up_status": 200,
		"headers": {
		     "origin": "http://localhost:3000"
		}
	}
    ],

    "storage": {
	 "type": "sqlite3",
	 "create": true,
	 "dsn": "sqlite.db"
    },

    "notifiers": [
    ]
}
```
When trying to run checkup, it gives following error.
2020/08/07 01:35:30 json: cannot unmarshal string into Go struct field Checker.headers of type []string

If i remove headers, then it runs perfectly ok. Tried different combination but to no avail.

Cloned latest master and this issue is appearing. Any help would be greatly appreciated. :)

**Comment by titpetric** [comment]
Judging by the error, headers should be specified as an array, can you try with:

~~~json
"headers": [
    "Origin: http://localhost:3000"
]
~~~

**Comment by titpetric** [comment]
Sorry, I was incorrect: the http.Headers type is `map[string][]string`, which means...

~~~json
"headers": {
    "origin": ["http://localhost:3000"]
}
~~~

I may improve this in the future. The JSON parser is strict enough that it doesn't want to parse a string into a slice of strings, so the only option is to pass the single value as an array.
