### ISSUE TITLE
'exec' type fails with "Error: fork/exec command: no such file or directory\nOutput: empty\n"

### ISSUE THREAD

**Issue by rrjanbiah** [sourcegraph/checkup#148]
Used config:

```json
{
  "type": "exec",
  "name": "No recent bounced mails",
  "command": "tail /var/log/mail.log | grep bounced",
  "must_not_contain": "bounced"
},
```

But, getting:

```json
{"title":"No recent bounced mails","endpoint":"tail /var/log/maillog | grep bounced",
"timestamp":1614061801645369152,
"times":[{"rtt":7930178,
  "error":"Error: fork/exec tail /var/log/maillog | grep bounced: no such file or directory\nOutput: empty\n"}],
"down":true}
```

This looks strange as some other commands like `/usr/pgsql-12/bin/pg_isready` working good. So, probably any other issue?

**Comment by titpetric** [comment]
The plugin doesn't support what you're trying to do, arguments are a
special field (array), and piping isn't supported. You can create a
standalone .sh file which does this. It would also be possible to invoke
"bash -c 'commands'" here, if you can manage to encode it to json :)

**Comment by rrjanbiah** [comment]
@titpetric Thank you so much for your quick reply. Much appreciated. Closing this now.
