### ISSUE TITLE
Change config_template.js "timeframe"

### ISSUE THREAD

**Issue by krishamoud** [sourcegraph/checkup#15]
First, thank you for this awesome project!

In the `config_template.js` it has the value `1 * time.Day` which is go syntax.  I had to dig around a little to find out that the time also needs to be in nanoseconds rather than milliseconds which was a little confusing.  

The `config_template.js` should have `86399999999806` (roughly 24 hours in nanoseconds) or something similar as the demo value for `timeframe` as well as a comment saying the unit of time IMO.  

This is all assuming I didn't miss anything obvious when I was first setting it up.

**Comment by mholt** [comment]
We could probably mention there that this is in nanoseconds, for sure.

**Comment by mholt** [comment]
@krishamoud Taken care of now, thanks. (The `time.*` values are defined in ns in checkup.js, so you may use them in config_template.js.)
