### ISSUE TITLE
Add time between checks to the same host

### ISSUE THREAD

**Issue by dhrp** [sourcegraph/checkup#16]
Can we add a configurable timeout between checks, when multiple checks are done to the same URL?

Some servers reject rapid requests when a page is requested in rapid succession. Squarespace is one such example. Since we are using a reverse proxy for that host I want to healthcheck my proxy.

**Comment by mholt** [comment]
Sure... do you think that would belong with HTTP checks specifically or any/all checks?

**Comment by dhrp** [comment]
I don't currently have a need for it, but can imagine you'd want this for other protocols as well. Let's say you're checking if your SIP server responds to an invite. (establishing a session often goes over TCP, not UDP).
