### ISSUE TITLE
Documentation on how to use local storage

### ISSUE THREAD

**Issue by theguythatrepeatedit** [sourcegraph/checkup#18]
Gentlemen, I tried out this one https://github.com/sourcegraph/checkup/pull/13

Go as far as generating the json files after adding this to the config
`"storage": {
        "provider": "fs",`

Left the config.js with the template values, but I suppose I need to change this too ?

The html statuspage fails with NS_ERROR_DOM_BAD_URI when trying to read the json files - how/where can I config these paths to be legit ?

Thanks guys

**Comment by mholt** [comment]
We're a little behind updating the docs here, sorry about that. @emersion can you help @theguythatrepeatedit until we get a chance to update the docs?

**Comment by gogosphere** [comment]
Don't we need to include fs.js in the index.html for it to be considered when rendering?
https://github.com/sourcegraph/checkup/blob/9a91b6ea2cfac915abb4c1a352ea79fdad4e8831/statuspage/index.html#L4-L14

**Comment by mholt** [comment]
Yes -- replace s3.html with fs.html.

**Comment by theguythatrepeatedit** [comment]
Hi again, yeah I changed that too. Forgot to mention
However var URL is undefined in fs.js 17 when you try to load localstorage

I'll try to hack it together in the meantime

**Comment by emersion** [comment]
The URL is defined in config.js, under the "storage" section.

**Comment by mesketh** [comment]
Hi guys, I too like @theguythatrepeatedit am trying to get a local storage 'fs' provider rigged.

I've got a build with fs support and it's dumping checkouts to a local dir and i've configured the 'url' property of the 'storage' item but, when I step through I noticed that in spite of this configuration the resolution of the checkup json files in this dir is via http and not a local file resolution:

```js
checkup.getJSON = function(url, callback) {
	var request = new XMLHttpRequest();
	request.open('GET', url, true);
	request.onload = function() {
		if (request.status >= 200 && request.status < 400) {
			var json = JSON.parse(request.responseText);
			callback(json, url);
		} else {
			console.error("GET "+url+":", request);
		}
	};
	request.onerror = function() {
		console.error("Network error (GET "+url+"):", request.error);
	};
	request.send();
};
```

Misunderstanding or gap?

**Comment by mholt** [comment]
Web pages can't just open arbitrary files on disk, the user would have to select each one. So a GET request is made instead.

**Comment by JonathanMH** [comment]
Hello! I'm not entirely certain this will be of any value to anyone, but the following changes got the local fs adapter working for me, I basically just diffed my changes from `master` and put it in a blog post: http://jonathanmh.com/using-sourcegraph-checkup-local-file-system-storage/ (I guess some googlers will end up here)

**Comment by mholt** [comment]
Thanks for the initiative @JonathanMH -- I want to work on the docs this weekend if I have a chance. :)

**Comment by mholt** [comment]
Docs will always be iterated on, but 506815fa0dfbbe13dd02ad17d206a151a1546d15 should address this.

**Comment by JonathanMH** [comment]
That's a really really good Readme change, was so happy to get the mails last night! :)
