### ISSUE TITLE
json: cannot unmarshal string into Go value of type time.Duration

### ISSUE THREAD

**Issue by hrwebasst** [sourcegraph/checkup#19]
This was happening to me with a timeout of `timout:"2s"` modifying timeout in checkup.json to `timeout: 2` fixed the issue

**Comment by mholt** [comment]
Oh, yes.... this is how Go marshals time.Duration values - they're int64 values, not strings.

**Comment by shurcooL** [comment]
In that case, wouldn't `timeout: 2` mean 2 nanoseconds? But it sounds like OP wanted 2 seconds.

**Comment by mholt** [comment]
Yeah, so Go serializes the value in nanoseconds
