### ISSUE TITLE
Feature request: support for HTTP redirects

### ISSUE THREAD

**Issue by oree** [sourcegraph/checkup#22]
I was expecting to be able to check for redirects using something like

```
{
        "type": "http",
        "endpoint_name": "Web root redirect",
        "endpoint_url": "http://website.com",
        "up_status": 302,
        "must_contain": "Location: https://website.com/",
        "attempts": 5
}
```

but alas, there's a [`CheckRedirect`](https://github.com/sourcegraph/checkup/blob/master/httpchecker.go#L176-L178) in the `DefaultHTTPClient` that (I guess) jumps in before we get to look at the `UpStatus` ...

I'm new to Go... Any pointers in how to make a pull request that would be reasonably configurable?

Could it be, that `CheckRedirect` is altogether superfluous, as there is an `UpStatus` check later anyways?

In that case I think we could just replace the existing CheckRedirect body with:
```
    return http.ErrUseLastResponse
```

**Comment by Jonchun** [comment]
With this commit, trying to install checkup gives me:

./httpchecker.go:177: undefined: http.ErrUseLastResponse

**Comment by mholt** [comment]
@Jonchun You need Go 1.7.

**Comment by Jonchun** [comment]
@mholt Thanks. 

Looks like it will need to be clarified when #9 is solved.
