### ISSUE TITLE
Limit number of days or entries checkup stores

### ISSUE THREAD

**Issue by cmpis** [sourcegraph/checkup#28]
Overtime, if you're using a small interval check, the number of json files could explode. Would be nice to keep a limited number of entries if we wanted to. 

Maybe this is a job for something else, but a config option built in would be nice.

**Comment by gogosphere** [comment]
https://aws.amazon.com/blogs/aws/amazon-s3-object-expiration/

**Comment by cmpis** [comment]
Ah, thank you! Would also be nice for the fs storage provider as well.

**Comment by gogosphere** [comment]
Sure, not being cheeky but having this in your daily crontab would do it as well.

find ./ -name *.json -mtime +5 -exec rm {} \;

I don't know if I would want checkup managing filesystem stuff for me, but that's just one persons (often wrong) opinion.  (+5 = 5 older than 5 days)

**Comment by cmpis** [comment]
Also the expiration works on a prefix. I could write in my own service to do the work of marking files to be expired, but currently I can't mark just the check files to be deleted.

Also there would need to be some automatic cleanup on the index.json so that the data doesn't become suddenly gone.

i.e. I want last 90 days and after 90 days I lose everything so the previous 89 days are gone too.

**Comment by cmpis** [comment]
Oh wait, I didn't see [this existed already.](https://github.com/sourcegraph/checkup/blob/master/s3.go#L24-L28) 

https://github.com/sourcegraph/checkup/blob/master/s3.go#L24-L28

**Comment by mholt** [comment]
If using S3, set CheckExpiry in your storage provider config and Checkup will clean up old files for you.
