### ISSUE TITLE
What type of license is LICENSE?

### ISSUE THREAD

**Issue by tedyoung** [sourcegraph/checkup#3]
The license appears to be non-standard, i.e., not in the set of APL, GPL, BSD, MIT, etc. This makes lawyers uncomfortable since they have to do more work to determine whether it's acceptable or not. Can you clarify this? http://choosealicense.com/ is a good place to start.

**Comment by mholt** [comment]
The LICENSE file is "New BSD" (which I think most/any OSS lawyer would recognize) but the CONTRIBUTING.md file says MIT license, which is confusing. /cc @beyang

**Comment by beyang** [comment]
Sorry about the confusion––hasty copy-paste job. The license has been updated to be MIT.

**Comment by tedyoung** [comment]
Thanks for the update. @mholt: The only problem I had was because there was no title (e.g., "New BSD" or "BSD 3-Clause") it was hard for me to identify. It's unfortunate that the identifier for the type of license isn't in their template.
