### ISSUE TITLE
Document usage with Minio

### ISSUE THREAD

**Issue by gabesullice** [sourcegraph/checkup#31]
I may add a PR for this myself, but in case anyone else wants to get started before I can I'm putting this issue here early :)

I would love to use this with https://www.minio.io/. Minio is an S3 compatible storage driver written in Go. You can deploy it to pretty much any VPS and use it as a stand-in for S3. Documenting a workflow with it would remove the implied dependency on AWS and let people host on their VPS of choice.

**Comment by beyang** [comment]
This is a great idea. The dependency on AWS is a very loose coupling (in fact, someone else already merged an alternative implementation that hits local FS).

You'll need to implement [a simple interface](https://sourcegraph.com/github.com/sourcegraph/checkup/-/def/GoPackage/github.com/sourcegraph/checkup/-/Storage). And here's the fully linked, jump-to-def-able code for the [FS-backed store](https://sourcegraph.com/github.com/sourcegraph/checkup@6c5c42ddf4d83a87fc2ea63b5cbf5360440f06e0/-/def/GoPackage/github.com/sourcegraph/checkup/-/FS)

**Comment by jiangytcn** [comment]
@gabesullice  is there any update about your PR ?

**Comment by titpetric** [comment]
Closing as stale, will revisit if somebody needs this.
