### ISSUE TITLE
Support for substitution in checks

### ISSUE THREAD

**Issue by intabulas** [sourcegraph/checkup#33]
Would be very handy to have some fixed substitutions in checks that that endpoints that contain things like dates in them could be inserted at check time.  For context I started to use checkup for testing endpoints locally before committing, and alot of our urls are date based and being able to check  "today" and "yesterday" endpoints without hardcoding "yesterday" would be so useful

As an example, with dates, maybe cray things like (I am making up the syntax on the fly, so..)

```
{utc:2006} or {now:2006-01-02}
```

where 2006 is a go time format string. Or maybe durations

```
{utcadd:-48h} or {nowadd:-48h}
```

for two days ago

**Comment by titpetric** [comment]
I'm closing this as obsolete/won't implement:

- obsolete: you can use the `exec` to execute a custom check script/binary,
- won't implement: templating of any kind for JSON (you could us external tooling like jsonnet for that)
