### ISSUE TITLE
PagerDuty integration

### ISSUE THREAD

**Issue by beyang** [sourcegraph/checkup#4]
As requested here: https://news.ycombinator.com/item?id=12240864

**Comment by mholt** [comment]
@ihortom It looks like you've implemented a PagerDuty Notifier: https://github.com/snowplow/checkup/commit/1da889a0d86edff7f3a0c8064d35a7ac55b83673

Is this something you want to see merged in? I think we'd welcome it.

**Comment by ihortom** [comment]
@mholt, we have made some significant changes to your core components to serve our own purposes. The PagerDuty notifier in our fork has [evolved](https://github.com/snowplow/checkup/blob/develop/pagerduty.go) to accommodate [SSL certificate check](https://github.com/snowplow/checkup/blob/develop/tlschecker.go) which we implemented quite differently from what you did. As a result, I'm afraid the code we evolved won't fit your project the way it is now.

However, you are very welcome to reuse the ideas we have come up with.

Mind you, we have also implemented OpsGenie notifier you can take onboard too: https://github.com/snowplow/checkup/commit/3fa9ed3043c076cf50f16607b09d796e68a59a72

**Comment by titpetric** [comment]
Closing this issue due to staleness, replaced with #128
