### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pbuzdin** [sourcegraph/checkup#45]
When new release (with fs support) will be uploaded?

**Comment by JonathanMH** [comment]
The current release has FS support, please see the post I scrambled up for clues:
https://jonathanmh.com/using-sourcegraph-checkup-local-file-system-storage/

/shameless self promo

**Comment by pbuzdin** [comment]
@JonathanMH where did you diff from?

**Comment by JonathanMH** [comment]
@pbuzdin : The diffs are

* a: repository state
* b: my changes

;)

**Comment by mholt** [comment]
I'm planning on a new release later this week sometime.

**Comment by mholt** [comment]
Docs updated in 506815fa0dfbbe13dd02ad17d206a151a1546d15, new release will be coming soon.

**Comment by mholt** [comment]
Here's the release! Assets have been uploaded. https://github.com/sourcegraph/checkup/releases/tag/v0.2.0
