### ISSUE TITLE
Is the project abandoned ?

### ISSUE THREAD

**Issue by vtrbtf** [sourcegraph/checkup#46]

**Comment by beyang** [comment]
Nope, still active! Is there a particular bug you're observing?

**Comment by vtrbtf** [comment]
@beyang Nope. But the last release is very old, the last commit is from 3 months ago

**Comment by mholt** [comment]
After the summer ended, I've been super busy with grad school and other open source projects as well -- I'm sure Sourcegraph will maintain it as needed; they're a good team!
