### ISSUE TITLE
Possible problem with testcase in checkup_test.go

### ISSUE THREAD

**Issue by ShashankYadav** [sourcegraph/checkup#48]
Hi,

I was going through checkup_test.go. In TestCheckAndStore(), we have defined `c := Checkup{
		Storage:          f,
		Checkers:         []Checker{f, f},
		ConcurrentChecks: 1,
		Timestamp:        time.Now(),
		Notifier:         f,
	}`  with ConcurrentChecks set to 1.

But in the following lines, we have:

`	for i := range f.stored {
		if i > 0 && f.stored[i].Timestamp != f.stored[i-1].Timestamp {
			t.Error("Expected timestamps to be the same, but they weren't")
		}
	}`

How do we expect the timestamps to be the same if only 1 check can be run at a time due to ConcurrentChecks=1?

**Comment by mholt** [comment]
See the docs for [Checkup.Timestamp](https://github.com/sourcegraph/checkup/blob/00c94905b0c76fba4633457c3c9a196b0b6c3aed/checkup.go#L31-L35): the test ensures that the timestamps are the same value because the checks were initiated at the same time.
