### ISSUE TITLE
Unmarshaling of time.Duration from JSON broken, documentation outdated

### ISSUE THREAD

**Issue by zweizeichen** [sourcegraph/checkup#51]
Using the latest version from `master` you can not configure varibles like `check_expiry` (see [fs.go](https://github.com/sourcegraph/checkup/blob/master/fs.go#L24)). Entering a value as shown in the documentation yields the following error:

> json: cannot unmarshal string into Go struct field FS.check_expiry of type time.Duration

Also the documentation indicates that there is a `timeout`parameter for HTTP checks, yet it does not exist (anymore?) in the current implementation. Setting this in the config has no effect.

**Comment by mholt** [comment]
@zweizeichen Sorry about this. The `check_expiry` field is a time.Duration value, which is expressed in nanoseconds. Unfortunately that doesn't translate very nicely into human-writable JSON, I know, but that's just how Go does it. (It's really a good system, but it does leave something to be desired when writing by hand.)

I've updated the docs and hopefully they're better now. We direct people to the Godoc (with direct links) which has the most correct, current explanation of each field that is available!
