### ISSUE TITLE
tcp: unknown Checker type

### ISSUE THREAD

**Issue by DerfOh** [sourcegraph/checkup#52]
I am getting this error when checking a tcp endpoint.
```
tcp: unknown Checker type
```
I am using the latest release.

My checkup.json:
```
{
    "checkers": [{
		"type": "tcp",
		"endpoint_name": "Example TCP",
		"endpoint_url": "google.com:80",
		"attempts": 5
	}]
}
```

**Comment by DerfOh** [comment]
I fixed it by building it from source

Had a hard time finding this in the docs so here's the process that I followed to get it built.

```
cd $GOPATH/src/github.com/sourcegraph/checkup/cmd/checkup
go get
go build
vim checkup.json
./checkup --help
./checkup
```

**Comment by mholt** [comment]
Sorry about this; I'll try to get a release out this week.

**Comment by DerfOh** [comment]
Thanks @mholt! Keep up the awesome work!

**Comment by mholt** [comment]
Doing a new release in just a bit.
