### ISSUE TITLE
GitHub storage provider

### ISSUE THREAD

**Issue by parkr** [sourcegraph/checkup#53]
Hey friends.

I recently found out that when my server reboots, vital services aren't booted by systemd. Womp. To prevent a prolonged outage of any of my services again, I have decided to setup `checkup`.

This project came to my attention some months ago when it was released. I liked it, but didn't want to pay Amazon for this service. The only other option was to host on my server, which is what I want to check in the first place. So that didn't work. I decided today that I would create a GitHub storage provider. The [code is here](https://github.com/parkr/checkup/tree/add-github-storage-provider) under `github.go`. It [publishes to a repo](https://github.com/parkr/status/commits/master) which has GitHub Pages enabled, so I can ensure [it will always be accessible](https://www.parkermoore.de/status/). Pages has pretty great uptime and is free.

The code is not pretty and I'm not confident 100% of it works, though I'm working on that now. I would be happy to clean it up and write proper tests, but I wanted to first gauge interest here. 

**Are you interested in seeing a GitHub storage provider as I described?**

**Comment by shurcooL** [comment]
I don't have short term plans to use this, but as a passerby, I just wanted to say: this is really damn cool @parkr!

**Comment by mholt** [comment]
Holy smokes, that's COOL!

Submit a pull request. :smile:

**Comment by parkr** [comment]
Pull request submitted. It is not ready to be merged by any means. I'm looking for feedback. If the code is not upstreamable (if you don't believe it can be accepted into this repo), then I'll go ahead and ship it as a separate library with a modified `cmd/checkup`.

**Comment by mholt** [comment]
Cool, I'll review it in a bit.
