### ISSUE TITLE
Add a machine-readable identifier to checkup.Result

### ISSUE THREAD

**Issue by McKael** [sourcegraph/checkup#59]
I'd like to have a basic UID in the Result struct.

I know *Title* is supposed to be a unique identifier, but it also should be human-friendly so it might contain spaces and special chars.

An alternative would be to use *Title* as the UID and add a *Description* field that would contain the user-friendly string.

Thoughts?  I can do a PR if you like the idea.

**Comment by mholt** [comment]
Probably a good idea, although maybe leave Title as-is and introduce a new ID field that we use instead? (If not set, maybe we can give it a default value or something based on its order in the config.)

**Comment by McKael** [comment]
Yes, introducing an ID field seems better.

Using a default value based on the order does not sound good, that would change the ID if the configuration file is rearranged, wouldn't it?
I'd suggest something like cleaning the title value to produce the ID, e.g. a lower-cased `s/[^a-zA-Z0-9_-]//g`...

But would you make use of this ID field in checkup itself, or would it be for the users of the library (in which case it wouldn't necessarily have to have a default value)?

**Comment by mholt** [comment]
Good points...

> But would you make use of this ID field in checkup itself, or would it be for the users of the library (in which case it wouldn't necessarily have to have a default value)?

Probably within checkup itself. I'm not quite sure how it would work yet, need to spend more time on that.

**Comment by McKael** [comment]
Ok, thanks!

**Comment by titpetric** [comment]
Closing due to staleness. If you still have a need for a UUID or some sort of ID in the checkup.Result field, please reopen the issue with more details and describe your use case. Thanks for understanding.
