### ISSUE TITLE
Logging is disabled

### ISSUE THREAD

**Issue by McKael** [sourcegraph/checkup#64]
`log.SetOutput(ioutil.Discard)` unsets the log package output unconditionally for all users of the checkup package.
I don't see the point of this and of the logger.go file.

If it is only for the command line client (and even there, it hides error messages so it isn't very useful), I guess it should be moved into the cmd directory...

**Comment by mholt** [comment]
The `-v` flag will print logs, that should do what you're looking for. :)

**Comment by McKael** [comment]
But why isn't the Discard in the cmd package as well?

I mean, if I import checkup in a project, logs get magically discarded... and I have to work around it.

**Comment by mholt** [comment]
I think it was just the preference of @parkr? I'm mobile so I didn't look it up and I might be wrong. You want logging on by default?

**Comment by McKael** [comment]
@mholt I'd like it not to be modified by an imported package; if it's off by default in the CLI tool then I guess it should be turned off by the CLI package, not by the imported library.

**Comment by mholt** [comment]
@McKael Oh, I see what you're saying. As usual, feel free to make a PR. :smile:

**Comment by shurcooL** [comment]
More context here: https://github.com/sourcegraph/checkup/pull/55#discussion_r131560273.

**Comment by McKael** [comment]
@shurcooL Thanks for the reference, I hadn't seen it.

@mholt I wouldn't mind doing a PR, but I'm not convinced disabling logging by default is correct either, even if it's only for the command line tool.

Let me give an example.  If I have a buggy configuration file with
```
    "storage": {
        "provider": "dummyStorageProvider"
    }
```
... let's see what happens:

```
% ./checkup -c /tmp/checkup-buggy.json
zsh: exit 1     ./checkup -c /tmp/checkup-buggy.json
```

Now with `--v` (which should really be `-v` and/or `--verbose`, but not `--v`...):
```
% ./checkup -c /tmp/checkup-buggy.json --v
2017/08/27 09:17:56 dummyStorageProvider: unknown Storage type
zsh: exit 1     ./checkup -c /tmp/checkup-buggy.json --v
```

Note: I've been there and it is very unfriendly, I didn't know about about the --v switch; I had to debug checkup just to find out I had a mistake in the configuration file and the error message was quietly discarded...

So my PR would rather be to be verbose by default, remove the `--v` flag and add `-q`/`--quiet`.

Please let me know if you agree with this. :)

**Comment by parkr** [comment]
Hey! I apologize for my change modifying the way error messages were shown.

I believe we have three alternatives to enabling logging for all consumers of this library:

1. Set `log.SetOutput(buffer)` and write the `buffer` to `stderr` in the event of a panic or `os.Exit(n >= 1)`
2. Use a logger with log levels, e.g. DEBUG, INFO, WARN, ERROR, etc to prevent this in the future
3. Create a new `checkup.Logger = log.NewLogger()` on the `checkup` package; or create a `Checkup.Logger` on the `checkup.Checkup` type which all the `checkup.Checker`s and `checkup.Storage` instances contained within it can utilize.

One of the above options would satisfy longer-term needs than remaining with the package-level `log` solution we have in place now.

**Comment by McKael** [comment]
Hi @parkr, thanks for the comment.

I don't like 1. as it seems to be a workaround and adds complexity to the package user.

2. looks good, as long as it does not impose the logger to the user.

And I like 3.  Maybe the user (here cmd) should set up it's own logger and pass it to the checkup package?

@mholt, any thoughts?
