### ISSUE TITLE
Missing index.json (404)

### ISSUE THREAD

**Issue by Bechrissed** [sourcegraph/checkup#68]
Hi,

i'm using the latest release on Ubuntu 16.04. When I run checkup the stdout outpot is fine. The data is also stored when using the --store flag.

Although when visiting the statuspage it show only a gray header with text loading. In Chrome console I see an ajax error that it can't find index.json. Is this a file a have to make myself? If so what should be in it? Should I generate it? If so, how?

PS. I'm using fs storage and using fs.js instead of s3.js in index.html

Kinda lost here, any help is appreciated :)

**Comment by mholt** [comment]
Did you modify config.js using https://github.com/sourcegraph/checkup/blob/master/statuspage/js/config_template.js to specify the URL to your check files? You'll need to configure a server like Caddy to serve those.
