### ISSUE TITLE
How to implement a Notifier

### ISSUE THREAD

**Issue by kellertobias** [sourcegraph/checkup#69]
I have absolutely no knowledge in golang. But I have quite a lot knowledge in python, node, php and some in java, c and c++.

I am trying to extend checkup to be able to send emails, but however I do it, I only get "unknown notifier type".

My steps were:

 - create a case in `MarshalJSON` and in `UnmarshalJSON` to be able to have a Notifier Type called "printLogger" (later, I'd notify a rest api or email server)
 - add a new file `printloggernotifier.go` that has the package on top, some imports and then the `type PrintLoggerNotifier struct {...` that only has one property, a prefix that will be prepended to the log.
 - i also altered the both lines in marshal and unmarhal that tells `unknown Notifier type` to include marshal and unmarshal (to know where excactly the problem happened).
 - I deleted the binary and rebuilt it, but sadly the output is still the same.

**Comment by mholt** [comment]
Just for a quick sanity check, do something crazy like add a bunch of gibberish to one of the source files and re-compile. Does compilation succeed?

**Comment by kellertobias** [comment]
-_- compilation succeeds. all the imports in the projects are from absolute urls -_-

**Comment by mholt** [comment]
Okay, so, that means something is wrong with your Go environment. Make sure GOPATH is set properly and that your source files are in $GOPATH/src/github.com/sourcegraph/checkup and that you're running `go build` in the proper directory.

**Comment by kellertobias** [comment]
well, for now, I have changed the paths to be relative.

**Comment by kellertobias** [comment]
If someone is interested, my code, I have written in the first 4 hours of using go (and is capably of sending mails via mandrill)

```
package checkup

import (
	"fmt"
	"time"
	m "github.com/keighl/mandrill"
)

var currentStatus []MinimalResult

// HTTPChecker implements a Checker for HTTP endpoints.
type PrintNotifier struct {
	// Name is the name of the endpoint.
	MandrillKey string `json:"mandrill_key"`

	// Name is the name of the endpoint.
	Receipts []string `json:"receipts,omitempty"`

	MailFrom string `json:"mail_from,omitempty"`
	MailFromName string `json:"mail_from_name,omitempty"`
}

type MinimalResult struct {
	Healthy  bool `json:"healthy,omitempty"`
	Degraded bool `json:"degraded,omitempty"`
	Down     bool `json:"down,omitempty"`
	Exists	bool `json:"exists,omitempty"`
}

// Check performs checks using c according to its configuration.
// An error is only returned if there is a configuration error.
func (c PrintNotifier) Notify(res []Result) (error) {
	t := time.Now()

	client := m.ClientWithKey(c.MandrillKey)

	fmt.Println("%v", res)
	fmt.Println("%v", currentStatus)

	if len(currentStatus) < len(res) {
		currentStatus = make([]MinimalResult, len(res))
	}

	for index, server := range res {
		var oldStatus = currentStatus[index]
	
		message := &m.Message{}
		message.FromEmail = c.MailFrom
		message.FromName = c.MailFromName

		for _, element := range c.Receipts {
			message.AddRecipient(element, "", "to")
		}

		title := server.Title
		url := server.Endpoint

		if server.Down && (!oldStatus.Exists || !oldStatus.Down) {
			message.Subject = fmt.Sprintf("WARNING: %s is Offline", title)
			message.Text = fmt.Sprintf("The server %s dissappeared at [%s].\nThe Url %s responded \n\n\n =============== \n %s \n ============== \n See System Status at http://...", title, t.String(), url, server)
			fmt.Println("Server Down ", title)
		} else if server.Degraded && (!oldStatus.Exists || !oldStatus.Degraded) {
			message.Subject = fmt.Sprintf("NOTICE: %s is Slow", title)
			message.Text = fmt.Sprintf("The server %s took very long to answer at [%s].\nThe Url %s responded \n\n\n =============== \n %s \n ============== \n See System Status at http://...", title, t.String(), url, server)
			fmt.Println("Server Slow ", title)
		} else if server.Healthy && (!oldStatus.Exists || !oldStatus.Healthy) {
			fmt.Println("Server came up right now", title)
		} else  {
			fmt.Println("No Status change ", title)
		}

		currentStatus[index] = MinimalResult{Down: server.Down, Degraded: server.Degraded, Healthy: server.Healthy, Exists: true}

		_, err := client.MessagesSend(message)

		if err != nil {
			return err
		}


	}

	return nil
}
```

**Comment by mholt** [comment]
Nice work. :) I'll close this then.
