### ISSUE TITLE
TLS certificate check?

### ISSUE THREAD

**Issue by alexanderdean** [sourcegraph/checkup#7]
Hi! Would you be open to merging an SSL certificate check (validity of cert / time till it expires) if one was contributed?

**Comment by mholt** [comment]
Sure, but how will you define Healthy, Degraded, and Down for a TLS certificate? (Don't call it SSL. :trollface:)

**Comment by alexanderdean** [comment]
* Healthy: `days_till_expiry` > `THRESHOLD`
* Degraded: `days_till_expiry` <= `THRESHOLD` && `days_till_expiry` > 0
* Down: `days_till_expiry` <= 0

?

**Comment by mholt** [comment]
That sounds good to me!

**Comment by mholt** [comment]
I'm working on this, will be pushing a simple TLS checker soon.

**Comment by alexanderdean** [comment]
Our engineer @ihortom has implemented this already in our (tactical, non-ideological) fork:

https://github.com/snowplow/checkup/commit/757a8d9b2e7239459fd13fb19415e18c34f42003

Let us know if you'd like it PRed...

**Comment by mholt** [comment]
Thanks for the link! I'll probably reference it but I've already got it done, just writing some tests now.

**Comment by ihortom** [comment]
@mholt - it's still in develop branch, not merged to master. I'm planning to merge it today.

**Comment by jessfraz** [comment]
I'm excited!

**Comment by mholt** [comment]
Okay, got a simple TLS checker implemented. Right now it's just the basic checks: connection latency, handshake timeouts, certificate expiration (near = degraded, past = down), that kind of thing. Can definitely be improved with a little more TLC. :smile:

**Comment by alexanderdean** [comment]
Awesome, thanks!
