### ISSUE TITLE
FreeBSD "-sh: checkup: not found"

### ISSUE THREAD

**Issue by reelsense** [sourcegraph/checkup#71]
This is what I get when trying to install:

`# pkg install go git ca_root_nss` _(go v1.9)_

`$ go get -u github.com/sourcegraph/checkup/cmd/checkup`

```
$ checkup --help
-sh: checkup: not found
```

Are there dependencies I'm missing?

**Comment by mholt** [comment]
It just means the checkup command isn't in your PATH. Make sure $GOPATH/bin is in your PATH.

**Comment by reelsense** [comment]
![](http://rs509.pbsrc.com/albums/s332/oceancurrents/__009facepalm.gif?w=280&h=210&fit=crop)

Aww, thank you.
