### ISSUE TITLE
Headers and auth for HTTP checks

### ISSUE THREAD

**Issue by mholt** [sourcegraph/checkup#8]
From: https://news.ycombinator.com/reply?id=12241719&goto=item%3Fid%3D12240380%2312241719

> Can we use custom headers/auth when setting up the APIs for health checkups?

This shouldn't be too hard to implement; just some more fields on the struct.

**Comment by intabulas** [comment]
I just did PR #32 for Header support, since it was an immediate need for me

**Comment by intabulas** [comment]
@mholt was going to follow on headers with auth support. You want to follow the similar pattern that was used for headers, ie: wrap username and password in a []string and then pass them to SetBasicAuth or in this case do you want a new struct type (ie: checkup.Authorization) that would allow for things like jwt tokens vs basic auth

**Comment by mholt** [comment]
@intabulas I love the effect of long walks in nature on debugging and development. 🌳  😄 

Its own struct/interface sounds like a good plan, I think it will be the most extensible/pluggable later that way.

**Comment by rrjanbiah** [comment]
@titpetric Looks like this is already merged 

https://github.com/sourcegraph/checkup/pull/32 
&
https://github.com/sourcegraph/checkup/blob/master/check/http/http.go#L70

FYI

**Comment by titpetric** [comment]
Headers yes, but not Auth.

It's possible that we don't need authentication helpers, which means that anybody who wants basic auth, JWT or any other authentication schema can implement their own handoff.

I'd close this as stale and reopen if there are feasible proposals at some point

cc @beyang

**Comment by rrjanbiah** [comment]
@titpetric With `exec` checker and `curl`, I think, we can handle almost all authentication.

**Comment by titpetric** [comment]
I'll close this issue, even without exec+curl headers can be set in the http checks, which means that you could also set any header key/value pairs that provide authentication. If the authentication flow is more complex, then exec+curl are your best bet. Feel free to open a new issue with feature requests, this one also dates to 2016 and might not be relevant today :)
