### ISSUE TITLE
Validating HTTPS against custom CAs

### ISSUE THREAD

**Issue by jeff-minard-ck** [sourcegraph/checkup#83]
I'd like to use checkup to monitor a slew of internal services we have, but they all are serving HTTP traffic using certs signed by our internal CA. When I run `checkup` on my mac (in which chrome can access the sites acceptably well) the application errors out that check with:

```
x509: certificate signed by unknown authority
```

How can I feed checkup the CA cert or get it to recognize system-wide installed items? (Perhaps this would work better if I ran it in a container with more "standard" ca-bundle locations?)

**Comment by jeff-minard-ck** [comment]
(Ah, yeah, as a docker container running a Centos7 base with our CA installed, checkup uses the systemwide cert just fine. Could just be a Mac issue then.)

**Comment by titpetric** [comment]
I'm closing the issue due to age, and what seems to be an user configuration issue. Checkup is tested with self-signed CA certs, so I'm reasonably sure that this isn't related to checkup. You're welcome to re-open the issue if it's still relevant for you.
