### ISSUE TITLE
slack: unknown Notifier type

### ISSUE THREAD

**Issue by damien-murphy** [sourcegraph/checkup#84]
When I add a slack notifier as per the documentation and run checkup I get the following error

slack: unknown Notifier type

**Comment by AlexFinn** [comment]
you should build from source I think because of the binaries were not built with latest changes as I see

**Comment by emcniece** [comment]
Confirmed - Slack notifier works when building from source .

**Comment by titpetric** [comment]
Closing as resolved, issue is not present if building from source. Releases have been removed, I'm not sure we'll have a pinned release in the future - building from source is suggested.
