### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by cweagans** [sourcegraph/checkup#86]
It looks like activity here has somewhat died off. Is this project still active? Are you looking for comaintainers?

I'm looking at deploying this for personal stuff, but I'd rather not base my monitoring on a project that's no longer maintained.

**Comment by emcniece** [comment]
I [made a pull request](https://github.com/sourcegraph/checkup/pull/93) the other day and it was merged fairly quickly. Looks like the maintainers are still active, they're probably just busy people.

**Comment by mholt** [comment]
> Looks like the maintainers are still active, they're probably just busy people.

This is accurate. :grin: Sorry

**Comment by rawtaz** [comment]
@mholt Hey Matt, just found out that you've been doing this project years ago. Nice work!

Just curious, on the same topic as this issue, is it only you that's maintaining it, or are there others as well? What about SourceGraph the company, have they lost interest? I see there's a bunch of PRs lingering as well as issues, it kind of seems a bit dead.

That said, even if it's dead, I think it seems like such a good foundation to build on for most simple needs that people should just start using it anyway, regardless of the status :P

**Comment by mholt** [comment]
Oh, right. I don't maintain this particular project anymore -- I'm active _on GitHub_, I just don't have time/sponsorship to work on this repo right now like I did a few years ago. I can't speak for Sourcegraph but I bet they'd be willing to accept volunteers?

I think this project is cool, so I could also accept sponsorships to continue working on it. But unless a lot of people chip in it's unlikely to happen without another corporate sponsorship.

**Comment by titpetric** [comment]
At the moment, the project is active, I'm taking over maintenance tasks at this time. If you have feature requests, open issues. Please open an issue before submitting a PR to discuss.

Closing issue as it's not actionable. Thank you for understanding :)
