### ISSUE TITLE
Missing build and test instructions

### ISSUE THREAD

**Issue by pires** [sourcegraph/checkup#9]
As per https://github.com/sourcegraph/checkup/blob/master/CONTRIBUTING.md#getting-started, there should be build and test instructions.

**Comment by bishgupp** [comment]
Re: Build and test instructions... I get an '...checkup.json..' file missing error message when I run the 'checkup.exe' on a 64bit Windows PC

**Comment by rileytg** [comment]
i use 
```
go run cmd/checkup/main.go 
go test .
```

**Comment by JonathanMH** [comment]
I've experienced, that if you don't clone the repo into the expected path, it will fail too:
```
cmd/checkup/main.go:3:8: cannot find package "github.com/sourcegraph/checkup/cmd" in any of:
	/usr/local/go/src/github.com/sourcegraph/checkup/cmd (from $GOROOT)
	/home/user/projects/go/src/github.com/sourcegraph/checkup/cmd (from $GOPATH)
```
Maybe that's a general go thing, I have no quite understood all the dependency management fully.

**Comment by mholt** [comment]
I hope these clarifications to the contributing guide help a bit.
